server:
  port:  8010
spring:
  application:
    name: scs-mall
  datasource:
    name: mall
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&amp
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  rabbitmq:
    host: 192.168.158.180
    port: 5672
    username: test
    password: test
    publisher-confirms: true
    virtual-host: light
mybatis:
  basepackage: com.runlion.scs.mall.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.spring: info

redis:
  database: 0
  host: 192.168.173.150
  password: 1234
  pool:
    max-active: 1000
    max-idle: 100
    max-wait: 1000
    min-idle: 0
    max-total: 50
  port: 6379
  timeout: 0

pagehelper:
  helper-dialect: Mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql

feign:
  hystrix:
    enabled: true


auth:
  user:
    token-header: Authorization
    pub-key:
      path: jwt/pub.key

config:
  bus: 消息总线测试

#推荐商品的属性 url（详情页的地址）  拼接
database:
  urldetails: http://www.hsmro.cn/product/detail.do?id=



appConfig:
  templateUrlBatch: http://192.168.173.155:8880/group1/M02/00/3B/wKitm1vf-VSANDI-AAAj_34gM4U36.xlsx

